runtime: python39  # Python 3.9 runtime

entrypoint: gunicorn -b :$PORT app:app  # Gunicorn server to host the Flask app

instance_class: F2  # Optional: F2 is fine, this is for better performance

env_variables:
  SECRET_KEY: 'your-secret-key'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
